apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ptlebl4lb-python-gitops
  description: This is GitOps manifest for ptlebl4lb-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ptlebl4lb-python
    janus-idp.io/tekton: ptlebl4lb-python 
    backstage.io/kubernetes-id: ptlebl4lb-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ptlebl4lb-python
