apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ptlebl4lb-python
  janus-idp.io/tekton: ptlebl4lb-python
  backstage.io/kubernetes-id: ptlebl4lb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ptlebl4lb-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
